#!/bin/bash

# proxy
# PROXY=http://1.1.1.1:8000/
if [ ! -z ${PROXY} ]; then
  export http_proxy=${PROXY}
  export https_proxy=$http_proxy
  export ftp_proxy=$http_proxy
  export rsync_proxy=$http_proxy
  export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
fi

# locale
export LANG=en_US.UTF-8

# prompt
Default="\e[0m"
DarkGray="\e[0;30m"
BDarkGray="\e[1;30m"
Red="\e[0;31m"
BRed="\e[1;31m"
Green="\e[0;32m"
BGreen="\e[1;32m"
Yellow="\e[0;33m"
BYellow="\e[1;33m"
Blue="\e[0;34m"
BBlue="\e[1;34m"
Purple="\e[0;35m"
BPurple="\e[1;35m"
Turquoise="\e[0;36m"
BTurquoise="\e[1;36m"
LightGray="\e[0;37m"
BLightGray="\e[1;37m"
# background colors
DarkGray_b="\e[40m"
Red_b="\e[41m"
Green_b="\e[42m"
Yellow_b="\e[43m"
Blue_b="\e[44m"
Purple_b="\e[45m"
Turquoise_b="\e[46m"
LightGray_b="\e[47m"
#export PS1="\\[${Purple}# \\[${Turquoise}\u \\[${LightGray}at \\[${Green}\h \\[${LightGray}in \\[${BYellow}\w \\[${LightGray}[ \t ] \n\\[${Red}\$\\[${Default} "
# export PS1="\[${Purple}\]# \
export PS1="\
\[${Blue}\]\u \
\[${LightGray}\]at \
\[${Green}\]\h \
\[${LightGray}\]in \
\[${Yellow}\]\w \
\[${LightGray}\][ \t ]
\[${Red}\]\$ \[${Default}\]"
