#!/bin/bash

BASHCFG=bashrc_customized

do_backup()
{
  tod=$(date +%Y%m%d%H%M%S)
  [ -f ${1} ] && mv ${1} ${1}.${tod}
}

echo "Customizing VIM config ..."
if [ -d ${HOME}/.vim ]; then
    cp -r ${PWD}/vim/* ${HOME}/.vim/
else
    cp -r ${PWD}/vim ${HOME}/.vim
fi

# ln -s ${PWD}/vim ${HOME}/.vim
do_backup ${HOME}/.vimrc
# ln -s ${PWD}/vimrc ${HOME}/.vimrc
cp vimrc ~/.vimrc

echo "Customizing bash config ..."
# customized bashrc
do_backup ${HOME}/.${BASHCFG}
cp ${BASHCFG} ~/.${BASHCFG}
echo -e "\n# customized bashrc" >> ~/.bashrc
echo ". ~/.${BASHCFG}" >> ~/.bashrc
# effect immediately
. ~/.${BASHCFG}

echo "Done"
