# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = '''
(bold green)$directory$git_branch$git_metrics$git_status$git_state$rust
$character(bold green)'''

# ▹(bold green) '''

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[\$](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[!](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[ruby]
disabled = true

[rust]
format = '/ [  $version](bold green) '

[nodejs]
disabled = true
format = '/ [ $version](bold green) '

[git_branch]
symbol = ' '

[scala]
disabled = true

[java]
disabled = true

[python]
disabled = true

[docker_context]
disabled = true
