[tools]
"github:BurntSushi/ripgrep" = "latest"
herdr = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:agent-browser" = "latest"
"npm:degit" = "latest"
"npm:esbuild" = "latest"
"npm:executor" = "latest"
"npm:opensrc" = "latest"
"npm:sirv-cli" = "latest"
